# undefine all aliases:  unalias -a
# undefine single alias: unalias <ALIAS>
# check if an alias is available: type <ALIAS>
# source .bashrc to load defined aliases again, aliases are not removed

# directory aliases
alias home='cd ~'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# search running processes
alias p='ps aux | grep'

# search files in the current folder
alias f='find . | grep '
alias fts='grep -Irl'

# full text search
ftext() {
        # -i case-insensitive
        # -I ignore binary files
        # -H causes filename to be printed
        # -r recursive search
        # -n causes line number to be printed
        # optional: -F treat search term as a literal, not a regular expression
        # optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
        grep -iIHrn --color=always "$1" .
}

# list commands
alias la='ls -Alh'  # show hidden files
alias lz='ls -lSh'  # sort by size
alias lt='ls -lth'  # sort by time

# tail
alias tail='tail -f -n 40'

# modified base commands
alias cp='cp -i'
alias mv='mv -i'
alias rm='trash -v'
alias mkdir='mkdir -p'
alias cls='clear'
alias ps='ps -axuf'

# network connections
alias openports='ss -tulpe'
alias extip='curl -s ifconfig.me'

# archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# systeminfos
alias os='cat /etc/os-release'

# Flatpak
alias chrome='flatpak run com.google.Chrome'
alias chromium='flatpak run org.chromium.Chromium'
